### ISSUE TITLE
Формат моделей

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#10]
### Формат вершины:

 * позиция
 * цвет вершины
 * нормаль
 * текстурные координаты

### Текстуры:

 * Diffuse map
 * Normal map
 * Specular map

Эти мапы грузятся в шейдер + направление источника света (пока что только direction lighting)
 
Какой формат выберем? Или лучше написать свой?
Тебе нужно, чтобы можно было экспортировать из 3dmax?

**Comment by ToxikCoder** [comment]
Мне бы желательна была бы возможность импортировать, мне так гораздо легче было бы. Какой формат выбрать я хз, какие бывают и как лучше сделать. Я думаю, что все эти характеристики должны быть у всех вершин, кроме может быть цвета вершин, хотя он наверное пригодится для всяких вспомогательных нерендерабельных объектов, если какой-нибудь редактор делать будем. Ещё надо бы сделать возможность импортировать fbx, я читал, типа сцены отдельно и объекты отдельно надо загружать

**Comment by xotonic** [comment]
Я раньше пытался fbx сделать. Но там есть только отдельный жирный FBX SDK от автостола. А самому писать парсер для него не вариант - спецификация закрыта. 

А во, щас нашел 

http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html

Ну по сути можно его поюзать, только пока для мешей.

**Comment by ToxikCoder** [comment]
Ну тогда можно через этот sdk загрузку и сделать моделей, если надо будет, ещё какие-нибудь добавить. Я так понимаю он ещё и материалы поддерживает, это может пригодиться. Надо будет разобраться в этом sdk. Ещё и анимация есть. А на 3ds ничего не нашёл?
