### ISSUE TITLE
Форма сохранения настроек

### ISSUE THREAD

**Issue by ToxikCoder** [HotCore-Studio/hot-project#11]
Предлагаю настройки сохранять в бинарном виде. И, чтобы легче считывать было, записывать в виде столбика значений типа:
1920-1080
True
True
4
6
0
False
и тд.
Просто заранее решить, в каком порядке это всё будет сохраняться

**Comment by xotonic** [comment]
Так лучше тогда структуру запилить типа ParamsToSave и просто эту структуру сохранять в бинарный
```c++
struct SaveParams
{
int ResolutionWidth;
int ResolutionHeight;
bool VSync;
//.......
};
```
