### ISSUE TITLE
Новая технология! Прорыв! Precompiled shaders!

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#12]
Лева, новая тема. 

Помнишь блобы из шейдеров, которые хранят байт код? 

Так вот, можно исходики компилить сторонней прогой, а в игру загружать уже скомпилированные блобы!

И не нужно будет компилить каждый раз при запуске. Збс идейка, да? Все нормальные люди давно уже так делают. В ведьмачке щас поглядел, там в SpeedTree лежат .psobj и .vsobj расширения.

**Comment by ToxikCoder** [comment]
Я нихуя не понял, но звучит классно

**Comment by xotonic** [comment]
Вот код из моего курсача: 

```c++
compileFromFile(ps_name, PS_entryPoint, PS_model, &psBlob);
	Debug::if_failed(
		dev->CreatePixelShader(psBlob->GetBufferPointer(), psBlob->GetBufferSize(), NULL, &pixelShader),
		"error creating pixel shader");

	psBlob->Release();
```

При инициализации вызывается все время функция `compileFromFile`, которая выводит из файла исходников бинарник шейдера в `psBlob`. Это происходит каждый раз при запуске игры - компилится каждый раз один и тот же код.

Так вот, я хочу этот psBlob компилировать отдельной утилитой и сохранять его ввиде файла, а в игру загружать этот файл

```c++
psBlob = loadFromFile("ps_simple.blob")

dev->CreatePixelShader(psBlob->GetBufferPointer(), psBlob->GetBufferSize(), NULL, &pixelShader),
		"error creating pixel shader");

	psBlob->Release();
```

`CompileFromFile` теперь ваще юзаться не будет, вместо этого она будет юзаться в этой утилите для компиляции. А в игруле будет очень быстро грузиться готовый шейдак.

Плюс к этой утилите можно будет добавить дополнительные фичи для отладки шейдеров, типа автокомпиляция и превью на кубике.

**Comment by ToxikCoder** [comment]
Так то норм, но как именно это нужно сохранять и считывать?

**Comment by xotonic** [comment]
Ну нужно получить указатель на байткод шейдера (` ID3D11Blob::GetBufferPointer`) и его размер (`GetBufferSize()`). Ну и собсно потом записать его в бинарный файл с нужным расширением.
