### ISSUE TITLE
Зачатки архитектуры

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#13]
Кароче, чтоб наш код не скатился в говно, предлагаю ввести граф состояний.

Зачем он нужен? Вот к примеру, как обрабатывать ввод в большой игре?
Школьник бы написал так:
```c++
bool isPause;
bool playerMounting;
bool invertoryOpened;
// ...

if (input.keyPressed(key_escape)) { isPause = true; }
if (input.keyPressed(key_i)) { inventoryOpended = true; }

//...
if (isPause) 
{ 
doSmth(); 
}
if (playerMounting) { doPlotvaTeleportationBehindPlayer(); }
if (invertoryOpened) { /*....*/ }
```

Кароч, полная хуйня. Если что-нибудь нужно будет добавить или изменить - увязнешь в этом дерьме по горло.

Как надо:
```c++

// Делаем класс контроллера
class PlotvaController : InputController
{
public:
void TurnLeft();
void TurnRight();
void Dismount();
void Bind(Input& i) // virtual from parent
{
i.AddKeyHandler(key_e, Dismount);
i.AddKeyHandler(key_a, TurnLeft);
i.AddKeyHandler(key_d, TurnRight);
}
void Unbind(Input& i) // virtual from parent
{
i.DeleteKeyHandler(key_e, Dismount);
i.DeleteKeyHandler(key_a, TurnLeft);
i.DeleteKeyHandler(key_d, TurnRight);
}
}

//класс состояния
class State
{
void AttachController(InputController* ic) { /*...*/}
void Activate()
 {
  controller.Bind(input);
 }
void Deactivate()
{
 controller.Unbind(input);
}
}

class StateManager
 {
 State* activeState;

void GoToState(State* newState)
{
activeState.Deactivate();
newState.Activate();
activeState = newState;
}
 }


/* и собсно потом */

State mounting(PlotvaController);
State walking(GeraltController);

stateMgr.GoToState(walking);
stateMgr.GoToState(mounting);
```

И теперь у нас в зависимости от состояния привязываются и отвязываются обработчики событий нажатия клавиш. 
Контроллеры можно разделить на более мелкие, типа SignController, ThirdPersonCamera Controller, и потом в состоянии задавать несколько контроллеров одновременно.
Можно с стейтам привязывать не только ИнпатКонтроллеры, но и, к примеру, подгрузку ресурсов при активации стейта (из главного меню в игру), постэффекты (состояние погружения в воду или оглушения), контроллеры музыкальных дорожек и пр.

Еще забыл, что у состояний может быть иерархическая структура (state playing содержит в себe walking и mounting) . То бишь когда мы пишем `stateMgr.GoToState(MainMenu)` у нас сначала деактивируется walking, потом playing, если структура такая:
![](http://i58.tinypic.com/2j5b629.png)

Позже запилю иерархию состояний нашего прожекта

**Comment by ToxikCoder** [comment]
По идее так и надо строить структуру, просто из-за того, что я такого ещё никогда не делал, я изначально хз, как лучше делать, надо бы читать всякие good practice
