### ISSUE TITLE
Ложный фулскрин

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#7]
Такую фишку просек у ААА проектов, они вместо фулскрина делают окно размером на весь экран без титла и рамок. 
Плюсы : 
 - нету переключения в фуллскрин и обратно
 - юзер может изи сворачивать и разворачивать игру без того же переключения в фулл
 - нормально работают системные оверлеи, типа регулирования громкости, чудо-кнопок и других приложений

Минусы:
 - окно может каким-то образом сместиться
 - чудо-кнопки, выползающие во время игры, будут нагревать пукан юзера
 - вроде слышал, что видюхи работают быстрее в фуллскрине, но в нашем проекте это не так критично, и хз, правда ли это

В общем, нужно сделать эту фичу

**Comment by ToxikCoder** [comment]
Ну вот допустим когда Far Cry 3 включаешь, там сначала появляется окно с тайтлом, иконкой и кнопками сворачивания и тд. и потом уже включается фулскрин. В моём варианте оно тоже сворачивается и разворачивается нормально, только дебаговские мэсседж боксы на заднем плане появляются, то есть приложение всегда впереди всех окон. Из-за того, что у свап чеина Windowed устанавливается на FALSE, приложение начинает отрисовку на полный экран, его уже никак не сдвинуть, да и чудо-кнопки эти у меня не вылазили

**Comment by xotonic** [comment]
Ну так это типо фуллскрин? Обычно при переключение идет где-то секунду и окно мелькает пару раз - выглядит некрасиво

**Comment by ToxikCoder** [comment]
Я проверил, сворачивается из фулскрина он нормально, без всяких мерцаний, и разворачивается также. Если в окне уже что-то будет рисоваться, то возможно по другому будет, я хз.
