### ISSUE TITLE
Это важно

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#8]
Лёва, к меня к тебе серьезный разговор 
![](http://risovach.ru/upload/2015/03/mem/kot_76942525_orig_.jpg)

Я нашел в коде это:

```c++
#define ERROR_MESSAGE_DIALOG_HEADER L"HotEngine Application:"
```

Используя #define, ты тянешь наш проект ко дну и лишаешь нас будущего.

Это путь безрассудных людей, запомни. Надеюсь, оба мы запомним этот разговор и будем использовать только константы со статической проверкой кода

```c++
const wstring ErrorMessageDialogHeader = L"aksjdhsakjdhkjsahd";
```

**Comment by ToxikCoder** [comment]
Прошу простить меня, давай забудем этот неприятный инцидент и просто устремимся к константному будущему. Но всё таки называть их надо бы в виде ERROR_MESSAGE_DIALOG_HEADER, это же всё таки  константы

**Comment by xotonic** [comment]
Обычно капсом названия макросов пишут, а не констант. Но пофиг.
