### ISSUE TITLE
Жидохаб ебу дал

### ISSUE THREAD

**Issue by xotonic** [HotCore-Studio/hot-project#9]
Ну собсно теперь все буду пихать в ижы.

Как теперь клонировать репозиторий правильно?

Я пишу так в пустой папке:

```
git clone https://github.com/HotCore-Studio/hot-project.git
```

мб правильно по другому?

**Comment by ToxikCoder** [comment]
Нахрена ты столько лейблов делаешь?))
Если у тебя на компе ничего нет: в пустой папке делаешь clone
Если у тебя есть репозиторий и ты хочешь получить изменения, но не слить с твоими ветками: fetch
Если хочешь получить изменения и слить с твоими ветками: pull. Типа делаешь pull, перед тем, как начать работать, работаешь, коммитишь. Я делаю pull, чтобы скачать твои изменения и применить их к своему проекту
